language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/TimeArduinoDue PLATFORMIO_CI_BOARDS_ARGS="--board=due"
    - PLATFORMIO_CI_SRC=examples/TimeGPS
    - PLATFORMIO_CI_SRC=examples/TimeNTP
    - PLATFORMIO_CI_SRC=examples/TimeRTC lib https://github.com/PaulStoffregen/DS1307RTC
    - PLATFORMIO_CI_SRC=examples/TimeRTCLog lib https://github.com/PaulStoffregen/DS1307RTC
    - PLATFORMIO_CI_SRC=examples/TimeRTCSet lib https://github.com/PaulStoffregen/DS1307RTC
    - PLATFORMIO_CI_SRC=examples/TimeSerial
    - PLATFORMIO_CI_SRC=examples/TimeSerialDateStrings
    - PLATFORMIO_CI_SRC=examples/TimeTeensy3 PLATFORMIO_CI_BOARDS_ARGS="--board=teensy31"

install:
    - pip install -U platformio
    - rm -rf ./linux
    
    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/#!/lib/show/416/TinyGPS
    - platformio lib install 416 421 422

script:
    - if [[ $PLATFORMIO_CI_BOARDS_ARGS ]]; then bash -c 'platformio ci --lib="." $PLATFORMIO_CI_BOARDS_ARGS'; else bash -c 'platformio ci --lib="." --board=uno --board=teensy20pp'; fi
